In [2]:
import numpy as np

In [7]:
ndarr = np.array([3, 4, -5])

print(ndarr)
print(ndarr.size) # 取得資料數量

[ 3  4 -5]
3


In [53]:
# 一維陣列
data = np.array([3, 2, 6, 4])
print(data)

data = np.empty(4)  # .empty 資料未指定
print(data)

data = np.zeros(3)  # .zeros 長度為 n 的 0 陣列
print(data)

data = np.ones(5, dtype=float)   # .ones 長度為 n 的 1 陣列
print(data)

data = np.arange(5) # .arange 長度為 n 的連續值陣列
print(data)

[3 2 6 4]
[2.12199579e-314 4.24399158e-314 1.06099790e-313 4.24399159e-314]
[0. 0. 0.]
[1 1 1 1 1]
[0 1 2 3 4]


In [21]:
# 二維陣列
data = np.array([ # 3*3 二維陣列
    [2, 3, 2],
    [1, 5, 2],
    [4, 2, 1]
])
print(data)

data = np.empty([3, 3]) # 3*3 的資料未指定二維陣列
print(data)

data = np.ones([2, 3]) # 2*3 的 1 陣列
print(data)

[[2 3 2]
 [1 5 2]
 [4 2 1]]
[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 5.39519685e-321]
 [1.42410974e-306 2.33419537e-312 2.44031977e-312]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
# 三維陣列
data = np.array([ # 2*2*2 三維陣列
   [
       [3,1], [1,2]
   ],
   [
       [2,5], [10,2]
   ]
])
print(data)

data = np.zeros([3, 1, 3]) # 3*1*3 的 0 陣列
print(data)

[[[ 3  1]
  [ 1  2]]

 [[ 2  5]
  [10  2]]]
[[[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]]


# Elementwise calculation

In [30]:
data1 = np.array([3, 2, 10])
data2 = np.array([1, 3, 6])

print(data1 + data2)
print(data1 * data2)
print(data1 > data2)
print(data1 == data2)

[ 4  5 16]
[ 3  6 60]
[ True False  True]
[False False False]


# Matrix calculation

In [36]:
data1 = np.array([
    [1, 3]
])

data2 = np.array([
    [2, -1, 3],
    [-2, 4, 1]
])

result = data1.dot(data2) # 內積
result = data1@data2 # 內積，python 3.5 後才能這樣寫
print(result)


result = np.outer(data1, data2) # 外積
print(result)

[[-4 11  6]]
[[ 2 -1  3 -2  4  1]
 [ 6 -3  9 -6 12  3]]


# Statistic

In [ ]:
data = np.array([
    [2, 1, 7],
    [-5, 3, 8],
])

print(data.sum()) # 相加所有資料
print(data.max())
print(data.min())
print(data.mean())
print(data.std())
print(data.cumsum()) # 逐值累加

print(data.sum(axis=0)) # 針對 column 做加總
print(data.sum(axis=1)) # 針對 row 做加總
print(data.max(axis=0)) # 針對 column 找最大值
print(data.max(axis=1)) # 針對 row 找最大值

# 統計函數都可以用 axis 參數針對 row or column 做運算

# 維度 & 形狀操作

In [73]:
# 觀察資料形狀 (列 & 欄)
data = np.ones(10)
print(data.shape)

data = np.array([
    [3, 1, 5],
    [1, 2, 3]
])
print(data.shape)

# 資料轉置 (Transpose)
data = data.T
print(data)

# 資料扁平化 (把資料拉成一維)
newdata = data.ravel()
print(newdata)

(10,)
(2, 3)
[[3 1]
 [1 2]
 [5 3]]
[3 1 1 2 5 3]


In [91]:
# 重塑資料形狀 (reshape)
data = np.array([
    [
        [2, 1, 3],[1, 2, 3]
    ],
    [
        [0, 2, 1],[8, 9, 10]
    ]
])

print(data.shape) # 2*2*3

data = data.reshape(3, 4) # 重塑成 3*4
print(data)

print('\n------ 我是分隔線 ------\n')

data = np.zeros(18).reshape(3, 6)
print(data)

print('\n------ 我是分隔線 ------\n')

data = np.arange(9).reshape(3,3)
print(data)

(2, 2, 3)
[[ 2  1  3  1]
 [ 2  3  0  2]
 [ 1  8  9 10]]

------ 我是分隔線 ------

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

------ 我是分隔線 ------

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 資料索引 (與 list 相同)

In [118]:
# indexing
data = np.array([1, 5, 2, 10])
print(data[1]) 


data = np.array([
    [0, 1],
    [10, -5],
    [2, 6]
])

print(data[1, 1]) # 取 -5


5
-5


In [131]:
# slicing 切片
data = np.array([-1, -5, 2, 3])

print(data[0:3]) # 取 index 0~2，包頭不包尾
print(data[:2]) # 從開頭到 index 1
print(data[2:]) # 從 index 2 開始取到最尾
print(data[:]) # 全都要

[-1 -5  2]
[-1 -5]
[2 3]
[-1 -5  2  3]


In [132]:
# 多維度切片
data = np.array([
    [0,1,2],
    [3,4,5],
    [5,4,3],
    [2,1,0]
])

print(data[1:3, 0:2]) # row 取 1~2；column 取 0~1
print(data[0:2, 1]) # index 配 slice

[[3 4]
 [5 4]]
[1 4]


In [147]:
# 使用 ... 代表全都要
data = np.array([
    [
        [8, 1, 3],
        [-5, 5, 2]
    ],
    
    [
        [0, 1, 6],
        [4, 4, -3]
    ]
])

print(data[0, ...])
print('-------------')
print(data[..., 1:3])


# note: 在維度不高的時候，用逗號分隔維度，用 : 決定要不要取全部就好了
# ... 的用途在於中間可以全部都省略

[[ 8  1  3]
 [-5  5  2]]
-------------
[[[ 1  3]
  [ 5  2]]

 [[ 1  6]
  [ 4 -3]]]


# 合併 (Stacking)

In [151]:
# vstack: vertical stacking, 就是把陣列向下合併
# hstack: horizontal stacking, 就是把陣列向右合併


arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
]) # 2*3

arr2 = np.array([
    [7, 8, 9],
    [10, 11, 12]
]) # 2*3

arr3 = np.array([
    [13, 14],
    [15, 16]
])

result1 = np.vstack((arr1, arr2)) # 要放 tuple
result2 = np.hstack((arr1, arr2))
result3 = np.hstack((arr1, arr2, arr3))

print(result1)
print(result2)
print(result3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9 13 14]
 [ 4  5  6 10 11 12 15 16]]


# 切割 (Split)

In [3]:
# vsplit: vertical split, 以第一個維度下去切割 (切 row), 所以這裡並不是垂直的刀往下切的意思, 而是 row by row 的切
# hsplit: horizontal split, 以第二個維度下去切割 (切 column), column by column 的切

# 將 ndarray 切割後放進一 list 中


arr = np.array([
    [2,4,6,8,10,12],
    [1,3,5,7,9,11]
])

result1 = np.vsplit(arr, 2) # row by row 切成兩份
result2 = np.hsplit(arr, 2) # column by column 切成三份
result3 = np.hsplit(arr, 3)

print(result1)
print(result2)
print(result3)


[array([[ 2,  4,  6,  8, 10, 12]]), array([[ 1,  3,  5,  7,  9, 11]])]
[array([[2, 4, 6],
       [1, 3, 5]]), array([[ 8, 10, 12],
       [ 7,  9, 11]])]
[array([[2, 4],
       [1, 3]]), array([[6, 8],
       [5, 7]]), array([[10, 12],
       [ 9, 11]])]


In [32]:
a = np.array([1, 3, 7, 8, 2, 6, 0, 1, 2])
np.where(np.diff(np.sign(np.diff(a))) == -2)[0] + 1

array([3, 5], dtype=int64)